name: llamabot
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.9
  - build
  - bump2version
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  - loguru
  # Utilities
  - pyprojroot
  - python-dotenv
  # CLI development
  - typer
  - typer-cli
  # Software testing
  - hypothesis
  - pytest
  - pytest-cov
  - coverage
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - panel
  - jupyter_bokeh
  - bokeh<=3.1.0
  - pyzotero
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - openai
      - langchain==0.0.189
      - llama_index<=0.5.27
      - mknotebooks
      - wget
      - outlines
