name: Ollama-specific checks

on:
  pull_request:
    branches: [main]

jobs:
  test-ollama:
    runs-on: ubuntu-latest
    name: Test Ollama Models

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama in background
        run: ollama serve &

      - name: Pull Microsoft's Phi3 model
        run: ollama pull phi3
