name: Daily test of the latest PyPI packages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run test suite (Python ${{ matrix.python-version }})

    strategy:
      matrix:
        python-version: [3.10.12, 3.11.4, 3.12]

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # 17 June 2023: Figure out a way to move testing deps to the `pip install -e .` step below.
        run: |
          python -m pip install --upgrade pipx
          pipx install llamabot

      - name: Test CLI
        run: |
          llamabot --help
